# Adapted from https://doc.mergify.io/examples.html#running-ci-pipelines-automatically
# Validate your changes with:
#   $ curl -F 'data=@.mergify.yml' https://gh.mergify.io/validate/

pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=main (3.8.6, ubuntu-18.04)
      - check-success=main (3.8.6, macos-10.15)
      - check-success=main (3.9.1, ubuntu-18.04)
      - check-success=main (3.9.1, macos-10.15)
    actions:
      merge:
        method: squash

pull_request_rules:
  - name: Be author's friend
    conditions:
      - author~=ubiratansoares
      - check-success=main (3.8.6, ubuntu-18.04)
      - check-success=main (3.8.6, macos-10.15)
      - check-success=main (3.9.1, ubuntu-18.04)
      - check-success=main (3.9.1, macos-10.15)
    actions:
      merge:
        method: squash
