name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Project checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1.2
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install dependencies
        run: make setup

      - name: Publish to Pypi
        run: make deploy token=${{ secrets.PYPI_TOKEN }}
